/** Swarm `last_event.type_id` → display key (soccer subset, finix `GAME_EVENTS_MAP`) */
export const GAME_EVENT_SOCCER: Record<number, string> = {
  1: 'Goal',
  2: 'RedCard',
  3: 'YellowCard',
  4: 'Corner',
  5: 'Penalty',
  6: 'Substitution',
  10: 'Period',
  20: 'BallSafe',
  21: 'DangerousAttack',
  22: 'KickOff',
  23: 'GoalKick',
  24: 'FreeKick',
  25: 'ThrowIn',
  26: 'ShotOffTarget',
  27: 'ShotOnTarget',
  28: 'Offside',
  29: 'GoalkeeperSave',
  30: 'ShotBlocked',
  100: 'NotStarted',
  101: 'FirstHalf',
  102: 'HalfTime',
  103: 'SecondHalf',
};
